### ISSUE TITLE
更に2点の質問があります

### ISSUE THREAD

**Issue by T154-dot** [makaishi2/profitable_ai_book_info#1]
赤石様

読者の山本恒雄と申します。

依然として不明で対応に困っているので、下記の2点についてアドバイス頂けませんでしょうか？

１）追試するためCSVデータが必要なのですが、ZIPファイルとCSVデータの具体的な入手の仕方が不明です。（例えば、P225のUCI画面から具体的にどうすればできるのか？）
２）P335以下で、NumPy、pandas、matplotlibなどを実習したいのですが、下方のimport文の記入をする場作りとそれまでにやるべき事が何なのかが分かりません。（新notebookでimportを命令しても作動しないのですが？）

お手数を取らせて申し訳ございませんが、ご返事をよろしくお願い申し上げます。

**Comment by makaishi2** [comment]
山本様、本書をご購入いただき、誠にありがとうございます。
いただいたご質問に関して、下記のとおり回答いたします。

> １）追試するためCSVデータが必要なのですが、ZIPファイルとCSVデータの具体的な入手の仕方が不明です。

本書の実習では、すべてのNotebookで学習データの入手から追いかけることができるようになっています。
例えば、ご質問いただいたp.225の実習の場合、入手元のURLは複数行に分割されていてわかりにくいのですが、下記のURLになっていて、このこともnotebookのコードからわかります。

```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00275/Bike-Sharing-Dataset.zip'
```

他の実習も全部同じ作りになっていますので、notebookのコードを追いかけてみてください。

> ２）P335以下で、NumPy、pandas、matplotlibなどを実習したいのですが、
> 下方のimport文の記入をする場作りとそれまでにやるべき事が何なのか

前提の実行環境は本編と同じで、Google Colaboratoryです。
また、notebook自体も本編同様、githubから取得可能です。
例えば、p.335から始まるnumpy実習の場合、l2_01_numpy.ipynbが、実習コードがすべて含まれているnotebookになっています。
本編の実習同様、まずは、こちらを読み込んで実行していただくのがいいかと思います。

以上、よろしくお願いいたします。
