### ISSUE TITLE
更に4点、分からないことがあります

### ISSUE THREAD

**Issue by T154-dot** [makaishi2/profitable_ai_book_info#2]
赤石様

先日ご質問とご回答をいただいた山本恒雄と申します。ご丁寧なアドバイスのお陰様で、実習が随分進み、大分感じが掴めてきました。

重ね重ねで済みませんが、下記へのアドバイスをもう一度頂けませんでしょうか？

Ａ）p252以降のProphetの扱いを、セル追加＆コード手入力でできなくもないようですが、もっと便利な方法がありませんか？

Ｂ）p257の前まではどうにか苦肉の手入力のコードで処せたのですが、INFOの行がエラー表示され、それ以降は全く実習ができませんでした。上記が叶えられれば助かるのかも知れませんが？

Ｃ）p274の実習をしたいのですが、notebookの中に見つけられませんでした。どんな名前でしょうか？（尚、p366でグラフ表示があると知り、どうやったか定か出ないのですが必要なexelデータは見つけてデスクトップにダウンロードしておきましたが・・・）

Ｄ）Bike-Sharingの実習のところで、正規化処理された変数が含まれていましたが、その要否の判断基準と、その場合の分母は一体何になっているのでしょうか？

PS：多分、もう1回で、質問（最後にしようと思っている実用的なことがあります・・・）は終わると思います。今しばらくお付き合いいただけると助かります。

**Comment by makaishi2** [comment]
ご質問いただきありがとうございます。

まず、本書を使った実習のやりかたで根本的なところを勘違いされているかもしれないので、お伝えしておきます。
前回の回答でお伝えしたように、本書は

　実行環境: Google Colab
　プログラム: Githubで提供されているNotebook

を使い、基本的には読み込んだNotebookですべてのセルに対してShift + Enterで実行をかけると、書籍と同じ結果が得られる仕掛けになっています。
A) , B), C) すべて 5.3節の内容ですので、その場合であれば、5.3節用のNoteook ch05_03_bike_sharing.ipynbをGoogle Colabに読み込んで、上から順にすべて実行してください。これだけで最後のコラムを含めてすべての本に出てくる結果が得られるはずです。
本の中のコードはこれがすべてということでなく、一部飛ばして重要な点のみを説明しています。
本に書かれているコードだけ、裸のnotebookで実行しようとするとわけのわからないことになりますので、ご注意ください。

D)に関しては、公開データセットになっている段階ですでに正規化されていたので、なぜと私に聞かれても正確なところはお答えできません。(データを作った人に聞かないと真意はわからないので)

どういう計算をしたかという質問であれば、下記のUCIデータセット説明ページ

https://archive.ics.uci.edu/ml/datasets/bike+sharing+dataset

に、次のような記述があるので、そのとおりということかと思います。

```
- temp : Normalized temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-8, t_max=+39 (only in hourly scale)
- atemp: Normalized feeling temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-16, t_max=+50 (only in hourly scale)
- hum: Normalized humidity. The values are divided to 100 (max)
- windspeed: Normalized wind speed. The values are divided to 67 (max)
```

どういうときに正規化するかに関しては、4.3節に説明をしておきました。
ポイントとしては、p.135の表4-3-2の中で「損失関数型」となっているアルゴリズムに対しては正規化は効果があり、「決定木型」となっているアルゴリズムでは正規化は不要ということになります。
