### ISSUE TITLE
「コロナ予測」を公開データの形式変更に追従

### ISSUE THREAD

**Issue by quiver** [makaishi2/profitable_ai_book_info#8]
書籍には含まれていませんが、追加事例 の「Prophetでコロナ陽性者予測をしよう」において、公開データのフォーマット変更に伴い、Notebookを実行できなくなっていたので、報告します。

- [Notebook](https://github.com/makaishi2/profitable_ai_book_info/blob/master/notebooks/%E3%82%B3%E3%83%AD%E3%83%8A%E4%BA%88%E6%B8%AC.ipynb)
- [Prophetでコロナ陽性者予測をしよう - Qiita](https://qiita.com/makaishi2/items/aa88ccdc87af3e45edd7)

## 問題

URL https://covid19.mhlw.go.jp/public/opendata/newly_confirmed_cases_daily.csv

厚生労働省のデータ・フォーマットが縦持ちから横持ちに変わっていました。

### OLD

<img width="371" alt="68747470733a2f2f71696974612d696d6167652d73746f72652e73332e61702d6e6f727468656173742d312e616d617a6f6e6177732e636f6d2f302f3230363133302f38376463376262302d313264362d633562372d393334612d6231323230333738336364642e706e67" src="https://user-images.githubusercontent.com/266641/147478034-9bc8f4a8-0496-4ed5-a0f9-2f9c525f07e7.png">

### NEW

![Screenshot 2021-12-27 at 14 06 42](https://user-images.githubusercontent.com/266641/147478021-d4ae573e-95bb-4886-9e5b-16486617c922.png)

## 修正

```
# 東京都で絞り込み
df2 = df.query('Prefecture == "Tokyo"')

# 余分な列の削除
#df3 = df2.drop('Prefecture', axis=1)
```
となっている箇所を

```
# 東京都で絞り込み
df3 = df[["Date", "Tokyo"]]
```

のように変更する必要があるかと思います。

**Comment by makaishi2** [comment]
@quiver 様、
ご丁寧なコメントをいただき、感謝いたします。
ご指摘はまったくそのとおりなので、Githubとqiitaの該当部分を修正しました。
 (ついでにReadmeのリンクがないことにも気付き、対応しました。)
 qiitaのこの記事、私の記事の中ではとても人気のあるもののようなので、早めに教えていただき、大変助かりました。
 引き続き、よろしくお願いいたします。
